# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'change_pwd.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_change_pwd_window(object):
    def setupUi(self, change_pwd_window):
        change_pwd_window.setObjectName("change_pwd_window")
        change_pwd_window.resize(400, 300)
        self.centralwidget = QtWidgets.QWidget(change_pwd_window)
        self.centralwidget.setObjectName("centralwidget")
        self.old_pwd_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.old_pwd_edit.setGeometry(QtCore.QRect(160, 80, 191, 31))
        self.old_pwd_edit.setText("")
        self.old_pwd_edit.setObjectName("old_pwd_edit")
        self.check_new_pwd_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.check_new_pwd_edit.setGeometry(QtCore.QRect(160, 180, 191, 31))
        self.check_new_pwd_edit.setText("")
        self.check_new_pwd_edit.setObjectName("check_new_pwd_edit")
        self.change_pwd_btn = QtWidgets.QPushButton(self.centralwidget)
        self.change_pwd_btn.setGeometry(QtCore.QRect(160, 240, 91, 31))
        self.change_pwd_btn.setObjectName("change_pwd_btn")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setEnabled(True)
        self.label_3.setGeometry(QtCore.QRect(80, 140, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(140, 20, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setEnabled(True)
        self.label_4.setGeometry(QtCore.QRect(60, 190, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(80, 90, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.new_pwd_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.new_pwd_edit.setGeometry(QtCore.QRect(160, 130, 191, 31))
        self.new_pwd_edit.setText("")
        self.new_pwd_edit.setObjectName("new_pwd_edit")
        change_pwd_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(change_pwd_window)
        self.statusbar.setObjectName("statusbar")
        change_pwd_window.setStatusBar(self.statusbar)

        self.retranslateUi(change_pwd_window)
        QtCore.QMetaObject.connectSlotsByName(change_pwd_window)

    def retranslateUi(self, change_pwd_window):
        _translate = QtCore.QCoreApplication.translate
        change_pwd_window.setWindowTitle(_translate("change_pwd_window", "修改密码"))
        self.change_pwd_btn.setText(_translate("change_pwd_window", "设置"))
        self.label_3.setText(_translate("change_pwd_window", "新密码"))
        self.label.setText(_translate("change_pwd_window", "修改密码"))
        self.label_4.setText(_translate("change_pwd_window", "确认密码"))
        self.label_2.setText(_translate("change_pwd_window", "旧密码"))
