# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'index.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_index_window(object):
    def setupUi(self, index_window):
        index_window.setObjectName("index_window")
        index_window.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        index_window.setFont(font)
        self.centralwidget = QtWidgets.QWidget(index_window)
        self.centralwidget.setObjectName("centralwidget")
        self.login_button = QtWidgets.QPushButton(self.centralwidget)
        self.login_button.setGeometry(QtCore.QRect(140, 360, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.login_button.setFont(font)
        self.login_button.setObjectName("login_button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(290, 150, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.register_button = QtWidgets.QPushButton(self.centralwidget)
        self.register_button.setGeometry(QtCore.QRect(520, 360, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.register_button.setFont(font)
        self.register_button.setObjectName("register_button")
        index_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(index_window)
        self.statusbar.setObjectName("statusbar")
        index_window.setStatusBar(self.statusbar)

        self.retranslateUi(index_window)
        QtCore.QMetaObject.connectSlotsByName(index_window)

    def retranslateUi(self, index_window):
        _translate = QtCore.QCoreApplication.translate
        index_window.setWindowTitle(_translate("index_window", "饭卡管理系统"))
        self.login_button.setText(_translate("index_window", "登录"))
        self.label.setText(_translate("index_window", "饭卡管理系统"))
        self.register_button.setText(_translate("index_window", "注册"))
