# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'top_up.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_top_up_window(object):
    def setupUi(self, top_up_window):
        top_up_window.setObjectName("topUp_window")
        top_up_window.resize(400, 300)
        self.centralwidget = QtWidgets.QWidget(top_up_window)
        self.centralwidget.setObjectName("centralwidget")
        self.card_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.card_edit.setGeometry(QtCore.QRect(140, 80, 191, 31))
        self.card_edit.setObjectName("card_edit")
        self.money_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.money_edit.setGeometry(QtCore.QRect(140, 130, 191, 31))
        self.money_edit.setObjectName("money_edit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(180, 20, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.up_btn = QtWidgets.QPushButton(self.centralwidget)
        self.up_btn.setGeometry(QtCore.QRect(150, 230, 91, 31))
        self.up_btn.setObjectName("up_btn")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setEnabled(True)
        self.label_4.setGeometry(QtCore.QRect(50, 180, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setEnabled(True)
        self.label_3.setGeometry(QtCore.QRect(50, 130, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(80, 80, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.type_comb = QtWidgets.QComboBox(self.centralwidget)
        self.type_comb.setGeometry(QtCore.QRect(140, 180, 71, 30))
        self.type_comb.setObjectName("type_comb")
        self.type_comb.addItem("")
        self.type_comb.addItem("")
        self.type_comb.addItem("")
        top_up_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(top_up_window)
        self.statusbar.setObjectName("statusbar")
        top_up_window.setStatusBar(self.statusbar)

        self.retranslateUi(top_up_window)
        QtCore.QMetaObject.connectSlotsByName(top_up_window)

    def retranslateUi(self, topUp_window):
        _translate = QtCore.QCoreApplication.translate
        topUp_window.setWindowTitle(_translate("topUp_window", "充值"))
        self.label.setText(_translate("topUp_window", "充值"))
        self.up_btn.setText(_translate("topUp_window", "充值"))
        self.label_4.setText(_translate("topUp_window", "充值方式"))
        self.label_3.setText(_translate("topUp_window", "充值金额"))
        self.label_2.setText(_translate("topUp_window", "卡号"))
        self.type_comb.setItemText(0, _translate("topUp_window", "微信"))
        self.type_comb.setItemText(1, _translate("topUp_window", "支付宝"))
        self.type_comb.setItemText(2, _translate("topUp_window", "银行卡"))
